name: Java CI with Maven

on:
  workflow_dispatch: {}
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install

      - name: Test Local Action
        uses: pradeepjaladi/github-action@v.0.0.1
        with:
          milliseconds: 1000
          url: ${{ vars.url }}
          username: ${{ vars.username }}
          password: ${{ secrets.password }}
          pattern: ${{ vars.pattern }}
